### ISSUE TITLE
Not downloading mods correctly

### ISSUE THREAD

**Issue by retep998** [DoubleDoorDevelopment/CurseModpackDownloader#1]
As of recently, whenever downloading a modpack using this program, all mods have a size of 0. It used to work just fine, but now it doesn't.

**Comment by Claycorp** [comment]
Curse is doing something funny with URL's. We have known about it for a few days but there hasn't time to get it fixed. This weekend perhaps Dries can look into it.

**Comment by dries007** [comment]
Hopefully fixed with #2

**Comment by retep998** [comment]
I don't think this has been fixed. I just downloaded a pack using 0.1.0.12 which is the newest build on jenkins, and all the mods are still empty files with a size of 0.

**Comment by dries007** [comment]
Oh dam, I'll test it properly next time.

**Comment by dries007** [comment]
It should be fixed and working now. If you come across issues again, feel free to let me know.
