### ISSUE TITLE
Buildscript integration

### ISSUE THREAD

**Issue by SimonMeskens** [DoubleDoorDevelopment/CurseModpackDownloader#3]
I'm using this in my modpack build script right now. Some features that I feel are missing right now to make full use of it:

- A setting that only downloads mods that aren't already in the folder, so I can kinda use it as a cache system that doesn't redownload the pack each time
- A setting that doesn't download the Forge jar, so I don't have to have a line that deletes it
- A setting that doesn't create a log, this is less important
- A feature to generate an instance.cfg and proper Forge patch file for MultiMC, also less important

**Comment by dries007** [comment]
I'll add all of this as options, but:
- The issue with only downloading mods that arn't there is that it results in duplicate mods.
- Idk about the instance.cfg & patch file. If you can send me some docs or reference, and I have some time, sure.

**Comment by dries007** [comment]
- Mods won't re-download if they exists already. (already in 0.1.0)
- `-ignoreExistingMods` or `-iem` to ignore existing mods (already in 0.1.0)
- Existing mods now don't cause re-download.
- `-noForge` or `-nf` skips the forge jar
- `-quiet` or `-q` skips all output not needed. (inlc the log file)

It now exists with 0 if all mods downloaded, 1 if not.

**Comment by SimonMeskens** [comment]
Thanks man, I should be able to set up my buildscript properly now

**Comment by SimonMeskens** [comment]
Yup, seems to be working fine, thanks. Does exactly what I want now. Closing issue.

**Comment by dries007** [comment]
Just letting you know, our v1 branch has been rewritten with support for MultiMC and archived mods files, when using some command line options. There is also much better support for updating existing installations. If you need info or changes, feel free to comment or open a new issue if you prefer.
