### ISSUE TITLE
Jenkins repo not compiling recent versions.

### ISSUE THREAD

**Issue by Speedy321** [DoubleDoorDevelopment/CurseModpackDownloader#4]
The latest version that the jenkins linked in the readme.md (https://jenkins.dries007.net/job/CurseModpackDownloader/) has available is almost 6 months old (unless i'm missing something obvious).
I'm fine compiling from source for now, but it would be great if the Jenkins could have the latest and greatest versions again ;)

Thanks for making this btw.

**Comment by dries007** [comment]
Thanks!

Jenkins config was wrong, fixed now, will close with empty commit to test.

**Comment by Speedy321** [comment]
thanks!
